<div class="c2Action">
	<div class="button button-c2Action large">
		<div class="button-background"></div>
		<div class="icon wcart">
		  <img src="{{media url="wysiwyg/wcart.png"}}" alt="shopping cart" />	
		</div>
		<div class="label">
		  <span>Drink the Magic</span> 
		  <strong>Order Now</strong>
		</div>
	</div>

	<div class="button button-c2Action large">
		<div class="button-background "></div>
		<div class="icon wfoods">
		  <img src="{{media url="wysiwyg/wfoods.png"}}" alt="whole foods logo" />
		</div>
		<div class="label">
		  <span>Also Available at:</span>
		  <strong>Whole Foods</strong></div>
		</div>
	</div>
</div>
