<div id="section-1-2" class="section-inner showcase right">
    <div class="showcase">
    <!-- Large Fruits around Main Image -->
      <div id="wm" class="fruit"></div>
      <div id="cc" class="fruit"></div>
      <div id="rp" class="fruit"></div>
      <div id="gp" class="fruit"></div>
      <div id="pn" class="fruit"></div>
      
    <img class="bottle" src="{{media url="wysiwyg/product.png"}}"/>
  </div>
</div>
