<section id="section-3" class="page-section">
  <!-- Right-hand description -->
  <div id="section-3-1" class="section-inner center">
	
    <!-- Left-hand stamp -->
    <div class="section-inner showcase center">
	  <div class="claim">
	    <img src="{{media url="wysiwyg/boxclosed.png"}}" class="bigBox">
	  </div>

	  <div class="claim-descriptions">
		<!-- 1098 resolution for the pieces to align -->
		<!-- <img src="images/cvegan.png" class="sticker cv"> -->
		<!-- <img src="images/cusa.png" class="sticker cu"> -->
		<!-- <img src="images/csugar.png" class="sticker cs"> -->
		<!-- <img src="images/ccarb.png" class="sticker cc"> -->
		<!-- <img src="images/cnongmo.png" width="6.5%" height="6.5%" class="sticker cg"> -->
		<!-- <img src="images/cnatural.png" width="4%" height="4%" class="sticker cn"> -->
	  </div>
  	</div>
	
  	<header class="finale">
	  <span class="heading-pre">Take charge of your health!</span>
	  <h1 class="head decor-center">Pick-up your box today</h1>
  	</header>

  </div>
</section>