<center><h1>Meet 24</h1></center>

<div class="about-container">

		<div class="nate">
			<!-- <img class="about-display" src="<?php echo $this->getViewFileUrl('images/demo/dummy11.png'); ?>" /> -->
			<h3> Nathan Rich </h3>
			<p class="byhead">A man not defined by his past and yet still embracing it. After all, the progress he has made is phenomenal. Completely revitalizing himself and becoming the man that he wanted to be. There was just one thing missing: an easy solution to staying healthy and fit. </p>
			
			<h4> What was your motivation for making 24-Hour Health? </h4>
			<p class="bytorso">I wanted an easier way to get all the vitamins and minerals I needed in my diet without having to take 300 invidivual supplements. Something I could grab if I was on the run and especially something that didn't taste like raw chemicals.</p>

			<h4> How has 24-Hour Health affected your life? </h4>
			<p class="bywaist"> It's not only taken a worry out of my mind, it's got me feeling more energized and faster. Gone are the days when I used to stress about still eating healthy even when I was in a huge rush to get back to business matters. This has truly made my life, not only healthier, but easier.</p>
		</div>
		<div class="natepic"></div>


		<div class="twofo">
			<h3> What makes this any different from other similar products? </h3>
			<p>Engineered with specific key factors in mind. Vegan friendly, no sugar, low calorie, and last but not least made in the USA. It wasn't easy to come up with a recipe combining everything and STILL having it taste good. A years worth of taste testing, ingredient extraction, and searching the world for the most wholesome sources has resulted in this.</p>

			<h4> Why do I even want this? </h4>
			<p> The everyday product for the everyday person. In the wonderful US of A. Specifically, Beverly Hills, California. Manufactured by SosoCouldBeFaster Industries Inc. in accordance with all the laws and whatnot. </p>

			<h4> Are all the ingredients natural? </h4>
			<p> </p>

			<h4> Does the product ever expire? When? </h4>
			<p> </p>
			<div class="natepic"></div>
		</div>

</div>











