
<h1>Here's the Scoop</h1>

<div class="blogbox-large">
	<div class="display-l">
	</div>
	<div class="desc-l">
		<h3>Superfruits and Super unhealthy Juice</h3>
		<p>Tired of feeling tired and run-down? Contrary to what many people think, health is something you can actually feel when you make the switch from an unhealthy lifestyle to a healthy one. Within the first week, most people report feeling a change in energy levels and overall mood. Its like they say, you are what you eat.</p>
		<br>
		<center><span class="readmo">Read More...</span></center>
	</div>
</div>

<div class="row">
	<div class="blogbox b1">
		<!-- <div class="display">
		</div> -->

		<div class="desc-ctrl">
			<h4>What your juice is missing</h4>
			<p>Find out why all these health crazed people are just switching from one fad diet to the next and learn what you can do to avoid it.</p>
			<br>
			<span class="readmo">Read More...</span>
		</div>
	</div>

	<div class="blogbox midbox b1">
		<!-- <div class="display"> -->
		<!-- </div> -->

		<div class="desc-shft">
			<h4>What your juice is missing</h4>
			<p>Find out why all these health crazed people are just switching from one fad diet to the next and learn what you can do to avoid it.</p>
			<br>
			<span class="readmo">Read More...</span>
		</div>
	</div>
	
	<div class="blogbox b3">
		<!-- <div class="display"> -->
		<!-- </div> -->

		<div class="desc">
			<h4>True meaning of Natural</h4>
			<p>Find out why all these health crazed people are just switching from one fad diet to the next and learn what you can do to avoid it.</p>
		</div>
	</div>
</div>

<div class="row">
	<div class="blogbox">
		<div class="display b4">
			<div class="shade"></div>
			<div class="desc-alt">
				<h4>Alcohol's Health Benefits</h4>
				<!-- <p>It turns out food has a huge impact on food. Ever been really hungry and accidentally popped off on someone? Sure, this is a drastic example but there are many minor changes going on in your mind that you may not even be aware of. Wait till you hear what they are...</p> -->
			</div>
		</div>

	</div>

	<div class="blogbox midbox">
		<div class="display b5">
			<div class="shade"></div>
			<div class="desc-alt">
				<h4>The hands of time</h4>
				<!-- <p>It turns out food has a huge impact on food. Ever been really hungry and accidentally popped off on someone? Sure, this is a drastic example but there are many minor changes going on in your mind that you may not even be aware of. Wait till you hear what they are...</p> -->
			</div>
		</div>
	</div>
	
	<div class="blogbox">
		<div class="display b6">
			<div class="shade"></div>
			<div class="desc-alt">
				<h4>Evolve into your better self</h4>
				<!-- <p>It turns out food has a huge impact on food. Ever been really hungry and accidentally popped off on someone? Sure, this is a drastic example but there are many minor changes going on in your mind that you may not even be aware of. Wait till you hear what they are...</p> -->
			</div>
		</div>
	</div>
</div>

<div class="row2">
	<div class="blogbox2 b2">
		<div class="desc1">
			<h4>Beating the Dead Horse</h4>
			<p>Same old routines to lose weight, get healthier, and start a new workout regiment. Stop beating the dead horse and find out the real trick to getting any of these routines to stick... <span class="readmo">Read More</span></p>
		</div>
	</div>

	<div class="blogbox2 border b2 midbox">
		<div class="desc1">
			<h4>Beating the Dead Horse</h4>
			<p>Same old routines to lose weight, get healthier, and start a new workout regiment. Stop beating the dead horse and find out the real trick to getting any of these routines to stick... <span class="readmo">Read More</span></p>
		</div>
	</div>
	
	<div class="blogbox2">
		<div class="display soon"></div>
		<div class="shade2"></div>
		<div class="desc-alt2">
			<h4>Wait till you see this...</h4>
			<!-- <p>It turns out food has a huge impact on food. Ever been really hungry and accidentally popped off on someone? Sure, this is a drastic example but there are many minor changes going on in your mind that you may not even be aware of. Wait till you hear what they are...</p> -->
		</div>
	</div>
</div>



