<div class="c2Action">
	<a href="http://24hrhealth.dev/index.php/liquid-vitamin.html">
	<div class="button button-c2Action large">
		<div class="button-background"></div>
		<div class="icon wcart">
  	  	  <img src="<?php echo $this->getViewFileUrl('images/wcart.png'); ?>" alt="shopping cart" />
		</div>
		<div class="label">
		  <span>Drink the Magic</span> 
		  <strong>Order Now</strong>
		</div>
	</div>
	</a>

	<div class="button button-c2Action large">
		<a href="http://24hrhealth.dev/index.php/workwith">
		<div class="button-background "></div>
		<div class="icon wfoods">
  	  	  <img src="<?php echo $this->getViewFileUrl('images/wfoods.png'); ?>" alt="Whole Foods logo" />
		</div>
		<div class="label">
		  <span>Retailer or Supplier?</span>
		  <strong>Bulk Options</strong></div>
		</div>
		</a>
	</div>
</div>
