<div class="c2Action">
	<div class="button button-c2Action large">
		<div class="button-background"></div>
		<div class="icon wcart">
  	  	  <img src="<?php echo $this->getViewFileUrl('images/wcart.png'); ?>" alt="shopping cart" />
		</div>
		<div class="label">
		  <span>Drink the Magic</span> 
		  <strong>Order Now</strong>
		</div>
	</div>

	<div class="button button-c2Action large">
		<div class="button-background "></div>
		<div class="icon wfoods">
  	  	  <img src="<?php echo $this->getViewFileUrl('images/wfoods.png'); ?>" alt="Whole Foods logo" />
		</div>
		<div class="label">
		  <span>Also Available at:</span>
		  <strong>Whole Foods</strong></div>
		</div>
	</div>
</div>
