<div class="navigation-overlay"></div>
<div class="main-nav-container" style="top: -100%;">
  	<div class="menuLogo">
  		<img width="80px" height="80px" src="<?php echo $this->getViewFileUrl('images/orangelogo1.png'); ?>"/>
  	</div>

  	<nav class="main-nav">
    	<ul class="site-links">
	 		<li><a class="nav--hover" href="https://24hourhealth.com/"><span>00</span>Home</a></li>
	  		<li><a class="nav--hover" href="https://24hourhealth.com/details"><span>02</span>Meet 24</a></li>
	  		<li><a class="nav--hover" href="https://24hourhealth.com/about"><span>04</span>My Account</a></li>
	  		<li><a class="nav--hover" href="https://24hourhealth.com/blog"><span>24</span>What's New</a></li>
	  		<li><a class="nav--hover" href="https://24hourhealth.com/press"><span>40</span>Press</a></li>
	  		<li><a class="nav--hover" href="https://24hourhealth.com/contact"><span>42</span>Contact</a></li>
		</ul>
		<ul class="store-downloads">
	  		<li><a>Questions or Concerns?</a></li>
	  		<li><a class="nav--hover" target="_blank" href="https://www.24hourhealth.com/contact">Call: <br>1-800-243-RICH</a></li>
	  		<li><a class="nav--hover" target="_blank" href="https://www.24hourhealth.com/contact">Email: <br>24HourHealth@Richbody.com</a></li>
  		</ul>
  	</nav>
	
  	<footer class="navigation-footer">
  		<ul class="social-buttons">
	  	  <li>
	    	<div class="button button-social">
		  		<a target="_blank" href="https://twitter.com/24hourhealth">
		  		<div class="button-background"></div>
		  		<div class="icon">
		    		<svg xmlns="http://www.w3.org/2000/svg" class="socI" viewBox="0 0 35.55 28.89">
						<path id="path" d="M35.55 3.42a14.53 14.53 0 0 1-4.19 1.15 7.31 7.31 0 0 0 3.21-4 14.61 14.61 0 0 1-4.63 1.77 7.3 7.3 0 0 0-12.43 6.65 20.71 20.71 0 0 1-15-7.62 7.3 7.3 0 0 0 2.26 9.74 7.27 7.27 0 0 1-3.3-.91v.09a7.3 7.3 0 0 0 5.85 7.15 7.33 7.33 0 0 1-1.92.25 7.21 7.21 0 0 1-1.37-.13 7.3 7.3 0 0 0 6.81 5.07 14.74 14.74 0 0 1-10.8 3 20.64 20.64 0 0 0 11.18 3.28c13.42 0 20.75-11.11 20.75-20.75v-.94a14.8 14.8 0 0 0 3.58-3.8z"/>
					</svg>
		  		</div>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
	    	<div class="button button-social">
		  		<a target="_blank" href="https://www.facebook.com/24hourhealth">
		  		<div class="button-background"></div>
		  		<div class="icon">
					<svg xmlns="http://www.w3.org/2000/svg" class="socI" viewBox="0 0 16.2 34.86">
						<path id="path" d="M16.2 11.29h-5.47V7.67a1.47 1.47 0 0 1 1.53-1.68h3.89v-6h-5.36c-6 0-7.31 4.46-7.31 7.31v4H.04v6.16h3.44v17.42h7.25V17.44h4.88z"/>
					</svg>
		  		</div>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
	    	<div class="button button-social">
	  	  		<a target="_blank" href="https://www.linkedin.com/company/24hourhealth">
		  		<div class="button-background"></div>
		  		<div class="icon">
					<svg xmlns="http://www.w3.org/2000/svg" class="socI" viewBox="15 15 30 30">
						<path id="path" d="M21.883 43.823v-18.3h-5.656v18.3h5.656zm0-24.785c-.034-1.637-1.125-2.884-2.898-2.884-1.773 0-2.932 1.247-2.932 2.884 0 1.602 1.125 2.885 2.864 2.885h.034c1.81 0 2.937-1.283 2.937-2.885zm9.227 24.785V33.397c0-.558.04-1.116.204-1.513.45-1.116 1.47-2.27 3.184-2.27 2.246 0 3.654 1.274 3.654 3.783v10.426h5.694V33.118c0-5.734-3.06-8.402-7.144-8.402-3.348 0-4.817 1.87-5.633 3.145l.04-2.442h-5.69c.082 1.752 0 18.41 0 18.41h5.685z"/>
					</svg>
		  		</div>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
			<div class="button button-social">
		  		<a target="_blank" href="https://www.youtube.com/user/24hourhealth">
		  		<div class="button-background"></div>
		  		<div class="icon">
					<svg xmlns="http://www.w3.org/2000/svg" class="socI" viewBox="0 0 22.79 16.03">
						<path id="path" class="129d6686-7d62-4638-b6f2-0be7ee8b1bba" d="M22.56 3.46a4.93 4.93 0 0 0-.91-2.26 3.26 3.26 0 0 0-2.28-1C16.18 0 11.4 0 11.4 0s-4.78 0-8 .23a3.26 3.26 0 0 0-2.28 1 4.93 4.93 0 0 0-.89 2.23A34.48 34.48 0 0 0 0 7.15v1.72a34.47 34.47 0 0 0 .23 3.69 4.93 4.93 0 0 0 .91 2.26 3.86 3.86 0 0 0 2.51 1c1.82.18 7.74.18 7.74.18s4.79 0 8-.24a3.26 3.26 0 0 0 2.28-1 4.93 4.93 0 0 0 .91-2.26 34.51 34.51 0 0 0 .23-3.69V7.15a34.51 34.51 0 0 0-.25-3.69zM9 11V4.57l6.2 3.21z" data-name="Lozenge"/>
					</svg>
		  		</div>
		  		</a>
		 	</div>
	  	  </li>

	  	  <li>
			<div class="button button-social">
		  		<a target="_blank" href="https://www.instagram.com/24hourhealth">
		  		<div class="button-background"></div>
		  		<div class="icon">
					<svg xmlns="http://www.w3.org/2000/svg" class="socI" viewBox="0 0 70 70">
						<path id="path" d="M61.92 29.62h-6.09a21.54 21.54 0 1 1-41.66 0H8.04v29.62a2.69 2.69 0 0 0 2.69 2.69h48.46a2.69 2.69 0 0 0 2.7-2.69V29.62zm0-18.84a2.69 2.69 0 0 0-2.7-2.69h-8.07a2.69 2.69 0 0 0-2.69 2.69v8.08a2.69 2.69 0 0 0 2.69 2.69h8.07a2.69 2.69 0 0 0 2.7-2.69v-8.08zM35.04 21.54A13.46 13.46 0 1 0 48.5 35a13.46 13.46 0 0 0-13.46-13.46M61.97 70H8.04a8.08 8.08 0 0 1-8-8.05V8.08A8.08 8.08 0 0 1 8.12 0h53.85a8.08 8.08 0 0 1 8.08 8.08v53.87a8.08 8.08 0 0 1-8.08 8.08"/>
					</svg>
		  		</div>
		  		</a>
			</div>
	  	  </li>
		</ul>
		
		<div class="copyright-container">
			<div class="copyright" data-stagger="" style="opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);">
				© 2016 24 Hour Health all rights reserved
			</div>
			<div class="crafted" data-stagger="" style="opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);">
				crafted by <a href="http://petarstojakovic.net/" target="_blank" class="link--hover">daniel barenboim™</a>
			</div>
		</div>
  	</footer>
</div>
