<div id="hamburger" class="hamburger is-inactive" style="opacity: 1;">
	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>
	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>
	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>

	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>
	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>

	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>
	<span class="hamburger--outer"><span class="hamburger--inner"></span></span>
</div>
