<div class="navigation-overlay"></div>

<div class="main-nav-container" style="top: -100%;">
  	<div class="menuLogo">
  		<h1 class="menu-sign">Menu</h1>
  		<!-- <img src="<?php echo $this->getViewFileUrl('images/orangelogo1.png'); ?>"/> -->
  	</div>
  	

  	<nav class="main-nav">
    	<ul class="site-links">
	 		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/launch/"><span></span>Home</a></li>
	  		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/about/"><span></span>Meet 24</a></li>
	  		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/customer/account"><span></span>My Account</a></li>
	  		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/blog/"><span></span>What's New</a></li>
	  		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/faq/"><span></span>FAQ</a></li>
	  		<li><a class="nav--hover" href="http://24hrhealth.dev/index.php/contact/"><span></span>Contact</a></li>
		</ul>
<!-- 		<ul class="store-downloads">
	  		<li><a>Questions or Concerns?</a></li>
	  		<li><a class="nav--hover" target="_blank" href="https://www.24hourhealth.com/contact">Call: <br>1-800-243-RICH</a></li>
	  		<li><a class="nav--hover" target="_blank" href="https://www.24hourhealth.com/contact">Email: <br>24HourHealth@Richbody.com</a></li>
  		</ul> -->
  	</nav>
	
  	<footer class="navigation-footer">
  		<ul class="social-buttons">
	  	  <li>
	    	<div class="button button-social">
		  		<a target="_blank" href="https://twitter.com/24hourhealth">
  					<img width="60px" src="<?php echo $this->getViewFileUrl('images/iconTT.jpg'); ?>"/>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
	    	<div class="button button-social">
		  		<a target="_blank" href="https://www.facebook.com/24hourhealth">
  					<img width="60px" src="<?php echo $this->getViewFileUrl('images/iconFB.jpg'); ?>"/>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
	    	<div class="button button-social">
	  	  		<a target="_blank" href="https://www.linkedin.com/company/24hourhealth">
		  		<div class="button-background"></div>
  					<img width="60px" src="<?php echo $this->getViewFileUrl('images/iconIG.jpg'); ?>"/>
		  		</a>
	    	</div>
	  	  </li>

	  	  <li>
			<div class="button button-social">
		  		<a target="_blank" href="https://www.youtube.com/user/24hourhealth">
  					<img width="60px" src="<?php echo $this->getViewFileUrl('images/iconIN.jpg'); ?>"/>
		  		</a>
		 	</div>
	  	  </li>

	  	  <li>
			<div class="button button-social">
		  		<a target="_blank" href="https://www.instagram.com/24hourhealth">
		  		<div class="button-background"></div>
  					<img width="60px" src="<?php echo $this->getViewFileUrl('images/iconYT.jpg'); ?>"/>
		  		</a>
			</div>
	  	  </li>
		</ul>
		
		<div class="copyright-container">
			<div class="copyright">
				© 2016 24 Hour Health all rights reserved
			</div>
			<div class="crafted">
				crafted by <a href="http://danielbarenboim.com/" target="_blank" class="link--hover">daniel barenboim™</a>
			</div>
		</div>
  	</footer>
</div>
