<div id="page-background">
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
	<div class="background-stripe"></div>
</div>

<div class="app-border border-top" style="width: 100%;"></div>
<div class="app-border border-right" style="height: 100%;"></div>
<div class="app-border border-bottom" style="width: 100%; left: 0%;"></div>
<div class="app-border border-left fix-border" style="height: 100%; top: 0%;"></div>
