<div id="section-1-1" class="section-inner description left">
	<header class="heading">	
	  <h1 class="head decorated">
	  <span class="font1">MAKING IT</span>
	  <span class="font2">EASY TO BE HEALTHY</span></h1>
	  <!-- <hr> -->
	</header>
	<p>24 Hour Health is designed for any health-conscious person who would like to see a drastic increase in their health. In a rush and don't have time to eat your daily serving of fruits and vegetables? Be responsible and grab a 24Hour Health to ensure your body is getting all the vitamins it needs.</p>
</div>
