<div id="section-1-2" class="section-inner showcase right">
    <div class="showcase">
    <!-- Large Fruits around Main Image -->
      <div id="wm" class="fruit"></div>
      <div id="cc" class="fruit"></div>
      <div id="rp" class="fruit"></div>
      <div id="gp" class="fruit"></div>
      <div id="pn" class="fruit"></div>
      
  	  <img class="boxopen" src="<?php echo $this->getViewFileUrl('images/boxopen.png'); ?>" />
	  <!-- <img class="bigBox" src="<?php echo $this->getViewFileUrl('images/boxclosed.png'); ?>"/> -->
  	  <!-- <img class="bottle" src="<?php echo $this->getViewFileUrl('images/product.png'); ?>" /> -->
  	</div>
</div>
