<section id="section-2" class="page-section">
	<div class="section-inner center">
		<h1 class="head decor-center">
            <span class="font1">EVERYTHING</span> <span class="font2">IN ONE PLACE</span></h1>
		<hr>

        <p class="description">24 Hour Health is a completely different and unique product to cover all your vitamins, minerals, fatty acids and fiber in a highly absorbable liquid blend that can be taken by anyone at any time (ages 12+). People don't have to worry about swallowing vitamin pills, or about getting an upset stomach. You can take 24 Hour Health during or after a meal or just take it like a snack - it's like taking a little shot of juice, it won't taste like you're chugging down nasty vitamins. Check out our superior ingredients! You will <b><u>NOT</u></b> be sorry that you did!</p>
		<!-- <p class="description">All of the vitamins and minerals your body needs are now available in a highly potent formula that comes in a small bottle. From Vitamin A to Zinc, 24 Hour Health gives you the best of many different meal types that might otherwise be very inconvenient to prepare each day.</p> -->
		<span class="helper">Click on one of the icons below to learn more.</span>

		<!-- Display Area -->
		<div class="showcase">
 			<div class="thePour">
    			<div id="mini" class="bb">
    				<img src="<?php echo $this->getViewFileUrl('images/Fblue.png'); ?>" val="Blueberries contain some very important ingredients that are beneficial for your health. The main thing that both our drink and blueberries share in common are the antioxidants that slowly enter the bloodstream and work for days to keep your immune system tough."/>
    			</div>

    			<div id="mini" class="av">
    				<img src="<?php echo $this->getViewFileUrl('images/Favocado.png'); ?>" val="Avocado's contain some of the healthiest forms of fat currently available. Didn't know there were healthy forms of fat? Well the omega family may have a big surprise for you."/>
    			</div>

    			<div id="mini" class="ln">
    				<img src="<?php echo $this->getViewFileUrl('images/Lemon.png'); ?>" val="Mr. Lemon has been the underdog for too long but no more. Lemons offer more than you could imagine in terms of health. Yellow fruits all contain some very special properties that can really help turn your gloomy day into a nice and sunny one."/>
    			</div>

    			<div id="mini" class="or">
    				<img src="<?php echo $this->getViewFileUrl('images/Orange.png'); ?>" val="The orange contains a large amount of Vitamin C. What is that good for, you may ask? Vitamin C greatly assists the immune system in fighting off infection and might be the best fruit you can choose when flu season comes around."/>
    			</div>

    			<div id="mini" class="cr">
    				<img src="<?php echo $this->getViewFileUrl('images/Fcarrot2.png'); ?>" val="You may have heard that carrots are good for your eyesight but our drink offers much more than that. We have the vitamins you need for your eyes, your heart, and even your mind. Tired of playing the rabbit? Take a shot like a boss instead."/>
    			</div>

    			<div id="mini" class="gr">
    				<img src="<?php echo $this->getViewFileUrl('images/grapes.png'); ?>" val="Grapes contain many components which make them taste both great and extremely beneficial for your health. Resveratrol is found in grapes, albeit in very small amounts, but these small doses of health are available in much larger quantities when you pop open a bottle of 24HH."/>
    			</div>

    			<div id="mini" class="bs">
    				<img src="<?php echo $this->getViewFileUrl('images/bs.png'); ?>" val="Healthy greens aren't always pleasing to eat and if you've ever spent time preparing food that you aren't excited to eat... then YOU, my friend, know the struggle. Fortunately, everything that the healthiest veggies contain can also be found in one easy go-to shot called 24HH."/>
    			</div>

    			<div id="mini" class="ap">
    				<img src="<?php echo $this->getViewFileUrl('images/Apple.png'); ?>" val="An apple a day keeps the doctor away. Bet you've heard that saying. Well 24HH compacts the health of a dozen apples and fits them all into one small bottle. Within this small shot lies the ability to not only keep the doctor away, but also the cardiologist, orthopedist, and neurologist."/>
    			</div>

    			<div id="mini" class="al">
    				<img src="<?php echo $this->getViewFileUrl('images/Falmond.png'); ?>" val="Almonds are one of the most overlooked health foods currently out there. You probably didn't know but almonds are full of different forms of Vitamin B and even some minerals. We decided to save you a little time and just took all the best vitamins out of a plethora of different nuts so that you can conveniently absorb them all after having 1 drink. Wow."/>
    			</div>
  			</div>
		</div>

		<img id="wavey" class="wave animate--clip-path" src="<?php echo $this->getViewFileUrl('images/wavey.png'); ?>" alt="wave effect"/>
	</div>
</section>