<div id="section-3-1" class="section-inner center">
    <div class="section-inner showcase center">
	  	<div class="claim">
	    	<img class="bigBox" src="<?php echo $this->getViewFileUrl('images/boxclosed.png'); ?>"/>
	  	</div>

	  	<!--
	  	<div class="claim-descriptions">
		1098 resolution for the pieces to align
		<img class="sticker cv" src="<?php echo $this->getViewFileUrl('images/cvegan.png'); ?>"/>
		<img class="sticker cu" src="<?php echo $this->getViewFileUrl('images/cusa.png'); ?>"/>
		<img class="sticker cs" src="<?php echo $this->getViewFileUrl('images/csugar.png'); ?>"/>
		<img class="sticker cc" src="<?php echo $this->getViewFileUrl('images/ccbar.png'); ?>"/>
		<img width="6.5%" height="6.5%" class="sticker cg" src="<?php echo $this->getViewFileUrl('images/cnongmo.png'); ?>"/>
		<img width="4%" height="4%" class="sticker cn" src="<?php echo $this->getViewFileUrl('images/cnatural.png'); ?>"/>
	  	</div>
	  	-->

  	</div>
	
  	<header class="finale">
	  <span class="heading-pre">Take charge of your health!</span>
	  <h1 class="head decor-center">Pick-up your box today</h1>
  	</header>

</div>
