<div class="section-inner showcase left">
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/vegan.png'); ?>"/>
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/sugar.png'); ?>"/>
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/usa.png'); ?>"/>
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/lactose.png'); ?>"/>
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/nongmo.png'); ?>"/>
	
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/gluten.png'); ?>"/>
</div>

<div id="section-3-1" class="section-inner description right">
	<header class="heading">	
	  <h1 class="head decorated">
	  <span class="font1">WE STAND</span><br>
	  <span class="font2">BY OUR CLAIMS</span></h1>
	  <!-- <hr> -->
	</header>
	<p>We designed this product with very particular criteria in mind. We refused to take shortcuts which is why we are now able to present to you, the bragging rights that very few others have. Sure, they may meet the criteria for one or two of these, but our claims are byfar unsurpassed. Don't settle for less.</p>
</div>

<header class="finale">
	<span class="heading-pre">Take charge of your health!</span>
	<h2 class="head decor-center">Pick-up your box today</h2>
</header>