<div class="section-inner showcase left">
	<img class="sticker" src="<?php echo $this->getViewFileUrl('images/usa.png'); ?>" val="All of our products are made in the USA. Not only does this gaurantee the best possible quality but it supports our local economy"/>
	<img class="sticker-small f" src="<?php echo $this->getViewFileUrl('images/sweetener.png'); ?>" val="All of our products are made in the USA. Not only does this gaurantee the best possible quality but it supports our local economy"/>
	<img class="sticker-small s" src="<?php echo $this->getViewFileUrl('images/nongmo.png'); ?>"val="All of our products are made in the USA. Not only does this gaurantee the best possible quality but it supports our local economy"/>
	<img class="sticker-small t" src="<?php echo $this->getViewFileUrl('images/vegan.png'); ?>" val="All of our products are made in the USA. Not only does this gaurantee the best possible quality but it supports our local economy"/>
	<img class="sticker-small z" src="<?php echo $this->getViewFileUrl('images/sugar.png'); ?>" val="All of our products are made in the USA. Not only does this gaurantee the best possible quality but it supports our local economy"/>
</div>

<div id="section-3-1" class="section-inner description right">
	<header class="heading">	
	  <h1 class="head decorated">
	  <span class="font1">WE STAND</span><br>
	  <span class="font2">BY OUR CLAIMS</span></h1>
	</header>
	<p>We created this product with your best interest at heart. We are passionate about others living life to the fullest, which starts with wellness created from the inside out. We have traveled far and wide, defeated dragons and power crazed wizards to prove that we are giving you the best of the best.
	See for yourself...</p>
	<!-- <p>We designed this product with very particular criteria in mind. We refused to take shortcuts which is why we are now able to present to you, the bragging rights that very few others have. Sure, they may meet the criteria for one or two of these, but our claims are byfar unsurpassed. Don't settle for less.</p> -->
</div>

<header class="finale">
	<span class="heading-pre">Take charge of your health!</span>
	<h2 class="head decor-center">Pick-up your box today</h2>
</header>